### PR TITLE
Fix right side menus that are generated from markdown headings

### LINKED ISSUE #192: Create navigation menus dynamically on internal pages
Work is already in progress here: https://github.com/onflow/next-docs-v1/pull/159

Create the navigation menus for all of the internal pages following the pattern established here: 
https://github.com/onflow/next-docs-v1/pull/161

### PR DESCRIPTION
**Pull request by schpet**
fixes #192, additionally

- Change dev:svg command to watch svg files for changes
- Adds jest

Screen Shot 2022-06-23 at 6 01 00 PM

Screen Shot 2022-06-23 at 6 01 03 PM

### CODE REVIEW

File: app/cms/utils/generate-toc.ts [hunk 1]
```diff
@@ -1,15 +1,62 @@
...
+        hash: link.url,
+        title: linkText,
+      })
+    } else if (child.type === "list") {
+      items.push(...processItems(child.children))
+    }
+  }
+
+  return items
 }
```
Comment (schpet) [inline app/cms/utils/generate-toc.ts:62]: fwiw this might not work for all markdown, but i feel like this is a good starting point and we can iterate on it

File: package.json [hunk 2]
```diff
@@ -93,7 +97,7 @@
     "dev": "run-p dev:*",
     "dev:css": "yarn generate:css -- --watch",
     "dev:remix": "remix dev",
-    "dev:svg": "yarn svgr --silent --template svgr/template.js --filename-case kebab --out-dir ./app/ui/design-system/images ./app/ui/design-system/images",
+    "dev:svg": "chokidar --silent --initial \"./app/ui/design-system/images/**/*.svg\" -c \"yarn svgr --silent --template svgr/template.js --filename-case kebab --out-dir ./app/ui/design-system/images ./app/ui/design-system/images\"",
```
Comment (schpet) [inline package.json:100]: this makes it so that the svgs are "watched" and also let me run this app through a Procfile

**Review by joekrill — APPROVED** [review]
👍

File: app/ui/design-system/src/lib/Components/InternalToc/index.tsx [hunk 3]
```diff
@@ -26,27 +26,22 @@ export function InternalToc({
...
-                    {title}
-                  </a>
-                </div>
-              )
-            })
-          : "No content"}
+        {headings.map(({ title, hash }, index) => (
+          <div className="flex" key={index}>
+            <a
+              href={hash}
```
Comment (alse) [inline app/ui/design-system/src/lib/Components/InternalToc/index.tsx:32]: Should this be scrolling the page to the heading?

**Review by alse — APPROVED** [review]

File: app/ui/design-system/src/lib/Components/InternalToc/index.tsx (hunk 3 above)
Comment (schpet) [reply app/ui/design-system/src/lib/Components/InternalToc/index.tsx:32]: yeah that's what it does, `hash` here is a url anchor, e.g. `#publickey`

image
