### PR TITLE
Fix office hours image

### LINKED ISSUE #378: Update Icons & Images
Upload the following logos from this [file](https://www.figma.com/file/Bf3brjLBdiunIH8IIfcWcr/Permissionless-Deployment?node-id=199%3A869)
image
- used for any playground icon.

image
- used as image for any playground cards (in the nav)

image
- (multiple sizes needed) - needs to display similar to the 'running man' logo of Cadence for FCL's 'homepage'
- used as default icon for FCL

image
- used as default for any tool/service that does not have a logo

image
- used as default for any article that does not have a logo

image
- (multiple sizes needed) - needs to display on the 'events' carousel where the large discord logo is right now.
image
- used as icon for dev-wallet tool
image
- (multiple sizes needed) - needs to display similar to the 'running man' logo of Cadence for FCL's 'homepage'
- used as default icon for node operation or spork-related callouts/cards.
image
- TBD usage, would just keep in multiple sizes for now in the repo for later use.

Landing page images to update:
Replace the landing page images with the images shown in the figma files for 'learn, community, tools':
image

### PR DESCRIPTION
**Pull request by aureentuluvacal**
Closes #378 for real

Had an issue loading the office hours image. Now it's resolved.

### CODE REVIEW

File: app/ui/design-system/src/lib/Components/EventCard/index.tsx [hunk 1]
```diff
@@ -3,6 +3,9 @@ import AppLink from "../AppLink"
 import { ButtonLink } from "../Button"
 import { Carousel, CarouselProps } from "../Carousel"
 import Tag from "../Tag"
+import OfficeHoursImage from "../../../../images/misc/office-hours@2x.png"
+
+export const OFFICE_HOURS_EVENT_TYPE = "Flow office hours"
```
Comment (alse) [inline app/ui/design-system/src/lib/Components/EventCard/index.tsx:8]: 👍

**Review by alse — APPROVED** [review]
